//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jalkahoitola_thesis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recieved_ammount
    {
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Price { get; set; }
        public string VendorName { get; set; }
        public string LocationCode { get; set; }
        public int SaapumiseranId { get; set; }
        public Nullable<int> UnitStock { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
